# .streamlit/secrets.toml

[connections.api]
dialect = "mysql"
host = "localhost"
port = 3306
database = "pets"
username = "root"
password = "root"

[api]
dialect = "mysql"
host = "localhost"
port = 3306
database = "pets"
username = "root"
password = "root"